FROM golang:1.20-alpine

RUN apk add --no-cache git

WORKDIR /app/dating-apps-srv-api

COPY ../go.mod .
COPY ../go.sum .

RUN go mod tidy

COPY ../. .

RUN go build -o ./dating-apps-srv-api cmd/api/main.go

EXPOSE 8070

CMD [ "./dating-apps-srv-api" ]

